services:
  container_ws_onboarding:
    build:
      context: .
      dockerfile: WS_Onboarding/Dockerfile.dev
    container_name: docker_ws_onboarding
    ports:
      - "5005:5005"
    depends_on:
      - container_db_onboarding
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__DefaultConnection=Data Source=container_db_onboarding;Initial Catalog=DB_Onboarding;User Id=sa;Password=OnboardingWorld2025;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;
    networks:
      - onboarding_net
    volumes:
      - ./WS_Onboarding:/app/WS_Onboarding
    restart: unless-stopped
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5005"]

  container_db_onboarding:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: docker_db_onboarding
    environment:
      SA_PASSWORD: "OnboardingWorld2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - onboarding_net
    volumes:
      - db_onboarding_data:/var/opt/mssql
    restart: unless-stopped

  container_fe_onboarding:
    build:
      context: ./FE_Onboarding
      dockerfile: Dockerfile.dev
    container_name: docker_fe_onboarding
    ports:
      - "5173:5173" # Vite
    volumes:
      - ./FE_Onboarding/src:/app/src # 🔥 Solo src para hot-reload
      - ./FE_Onboarding/public:/app/public # Archivos públicos
      - ./FE_Onboarding/index.html:/app/index.html # HTML principal (Vite)
      - ./FE_Onboarding/vite.config.js:/app/vite.config.js # Config de Vite
      - /app/node_modules # ⚠️ NO sobrescribir node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    networks:
      - onboarding_net
    depends_on:
      - container_ws_onboarding
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # ✅ Necesario para hot-reload
      - WATCHPACK_POLLING=true # ✅ Necesario para hot-reload

networks:
  onboarding_net:

volumes:
  db_onboarding_data:
