# Imagen base con Node.js
FROM node:23-alpine AS dev

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia solo los archivos de dependencias para aprovechar cache
COPY package*.json ./
RUN npm install

# Copia el resto del código fuente
COPY . .

# Variables de entorno opcionales para el desarrollo
# ENV NODE_ENV=development
# ENV HOST=0.0.0.0

# Expone el puerto típico (Vite: 5173, CRA: 3000, Next.js: 3000)
EXPOSE 3000
EXPOSE 5173

RUN npm run build

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]