DBCC CHECKIDENT ('Paises', RESEED, 0);
DBCC CHECKIDENT ('Roles', RESEED, 0);
DBCC CHECKIDENT ('Usuarios', RESEED, 0);
DBCC CHECKIDENT ('Servicios', RESEED, 0);
DBCC CHECKIDENT ('Clientes', RESEED, 0);
DBCC CHECKIDENT ('Contratos', RESEED, 0);
DBCC CHECKIDENT ('Contrato_Servicios', RESEED, 0);